site_name: Platform
site_url: https://www.codbex.com/

nav:
  - Home: 'index.md'
  - Products:
    - 'products/index.md'
    - Atlas: 'products/atlas.md'
    - Helios: 'products/helios.md'
    - Hades: 'products/hades.md'
    - Oceanus: 'products/oceanus.md'
    - Theia: 'products/theia.md'
    - Hyperion: 'products/hyperion.md'
    - Iapetus: 'products/iapetus.md'
    - Kronos: 'products/kronos.md'
    - Gaia: 'products/gaia.md'
  - Pricing: 'pricing/index.md'
  - News: 'news/index.md'
  - About: 'about/index.md'
  - Contact: 'contact/index.md'

theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo.svg
  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css
  - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

copyright: Copyright © 2023 codbex ltd

extra:
  homepage: https://www.codbex.com/
  analytics:
    provider: google
    property: G-QWPZ5B9RH8
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codbex/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codbex/
    - icon: fontawesome/brands/github
      link: https://github.com/codbex/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCbxnGOhmcDvBIrafDeyCU7Q/videos/
    - icon: fontawesome/brands/slack
      link: https://slack.dirigible.io